name: Super-Linter

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs: 
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Display environment variables
        run: printenv

      - name: Verify repository token
        run: echo $GITHUB_TOKEN | wc -c

      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




